[package]
name = "safe_linked_list_rust"
version = "0.1.0"
authors = ["Visualcode-t"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[example]]
name = "sample"
path = "examples/sample/sample.rs"